# 平台配置
platforms:
  # 飞书
  feishu:
    ai_model: "doubao"  # 该平台使用的总结模型
    app_id: ""
    app_secret: ""
    bot_token: ""
    target_chat_id: ""
    tasklist_guid: ""
    oauth_redirect_uri: "http://127.0.0.1:8001/callback"
    standup_time: "09:00"
    standup_timezone: "Asia/Shanghai"
    base_url: "https://open.feishu.cn"
  # 企业微信
  wecom:
    ai_model: "doubao"
    corp_id: ""
    corp_secret: ""

# AI 模型配置
models:
  doubao:
    name: "豆包大模型"
    api_key: ""
    base_url: ""
    model: ""
    params:
      timeout: 3 # 设定3分钟超时
  glm:
    name: "智谱清言大模型"
    api_key: ""
    base_url: ""
    model: ""
    params:
      timeout: 10 # 智普的大模型思考和回答的时间可能会久一点

# 代码仓库配置
repos:
  gitlab:
    token: ""
    base_url: "http://git.b2bwings.com"
    target_user: ""
    repos:
      - path: "frontend_b2bwings/b2b-wings-composite"
        branch: "test"
        name: "村才后台管理系统"
      - path: "frontend_b2bwings/b2b-wings-easyloan-mini"
        branch: "master, liangan"
        name: "农融易小程序"
        # 爬取日期配置（不传则默认爬取当天）
        # 支持单个日期或日期区间，每个元素以逗号分隔起止日期
        crawl_dates:
          - "2026-01-01, 2026-01-31"
      - path: "frontend_b2bwings/b2b-wings-easyloan-admin"
        branch: "test"
        name: "农融易后台管理系统"

# 启用的工作流，名称要和 platforms 中的 key 对应
enabled_workflows: ["feishu"]

# 通用配置（无分类前缀）
log:
  level: "INFO"
